spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password= chocolatefrog

spring.jpa.hibernate.ddl-auto= validate

path.to.avatars.folder= avatars

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

logging.level.ru.hogwarts.school.service=DEBUG
logging.level.ru.hogwarts.school.controller=DEBUG
logging.level.ru.hogwarts.school.repository=DEBUG

server.port=8081